# Generated by Django 5.1.2 on 2024-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_pagemaster_page_url_pagemaster_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=40),
        ),
    ]
